# Generated by Django 5.2.8 on 2025-12-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_programstudy', models.CharField(max_length=150, verbose_name='Nama Program Studi')),
                ('about_programstudy', models.TextField(verbose_name='Tentang Program Studi')),
                ('cover_header', models.ImageField(blank=True, null=True, upload_to='prodi_covers/', verbose_name='Cover Header Prodi (Gambar)')),
                ('name_hima', models.CharField(max_length=150, verbose_name='Nama Himpunan Mahasiswa')),
                ('cover_hima', models.ImageField(blank=True, null=True, upload_to='hima_covers/', verbose_name='Cover/Logo HIMA (Gambar)')),
                ('description_hima', models.TextField(verbose_name='Deskripsi HIMA')),
                ('kaprodi_profile', models.ImageField(blank=True, null=True, upload_to='kaprodi_profiles/', verbose_name='Foto Profil Kaprodi (Gambar)')),
                ('kaprodi_name', models.CharField(max_length=100, verbose_name='Nama Kaprodi')),
                ('kaprodi_description', models.TextField(verbose_name='Deskripsi Kaprodi')),
            ],
            options={
                'verbose_name': 'Program Studi',
                'verbose_name_plural': 'Daftar Program Studi',
            },
        ),
    ]
