# Generated by Django 5.2.8 on 2025-12-10 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Judul Header')),
                ('description_short', models.TextField(verbose_name='Deskripsi Singkat (Ringkasan)')),
                ('description_full', models.TextField(verbose_name='Deskripsi Lengkap')),
                ('image', models.ImageField(blank=True, null=True, upload_to='header_images/', verbose_name='Gambar Header')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_contents', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
            ],
            options={
                'verbose_name': 'Konten Header',
                'verbose_name_plural': 'Konten Header',
                'ordering': ['-created_at'],
            },
        ),
    ]
